
export enum ColumnTypeEnum
{
  // BLOB
  BLOB = "BLOB",
  TINYBLOB = "TINYBLOB",
  MEDIUMBLOB = "MEDIUMBLOB",
  LONGBLOB = "LONGBLOB",
  // DATE
  DATE = "DATE",
  // DATETIME
  DATETIME = "DATETIME",
  // DECIMAL
  DECIMAL = "DECIMAL",
  DOUBLE = "DOUBLE",
  // ENUM
  ENUM = "ENUM",
  // INT
  INT = 'INT',
  TINYINT = 'TINYINT',
  SMALLINT = 'SMALLINT',
  MEDIUMINT = 'MEDIUMINT',
  BIGINT = 'BIGINT',
  // STRING
  CHAR = "CHAR",
  VARCHAR = "VARCHAR",
  TEXT = "TEXT",
  TINYTEXT = "TINYTEXT",
  MEDIUMTEXT = "MEDIUMTEXT",
  LONGTEXT = "LONGTEXT",
  // TIME
  TIME = "TIME"
}
